-- AUTO-GENERATED by db/build-heroes-seed.mjs
-- The 10 hand-curated hero recipes from constants/products.ts.
begin;

insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('bathroom-cleaner', 'Bathroom Cleaner', 'Cleaning', 'cleaning', 'Easy', '4 min', '["1 ½ cups Distilled water","2 tbsp Castile soap","1 tbsp Baking soda","½ cup White vinegar","8 drops Tea tree oil","6 drops Lavender oil"]'::jsonb, '["Pour distilled water and white vinegar into a clean spray bottle.","Add castile soap and gently swirl — do not shake hard.","Sprinkle baking soda in, then close and rotate to combine.","Add tea tree and lavender oils.","Label the bottle with the date and store under the sink."]'::jsonb, true, '$3.20 saved', '["Baby-safe","Pet-safe","family-safe","spray"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('glass-cleaner', 'Glass Cleaner', 'Cleaning', 'cleaning', 'Easy', '3 min', '["1 cup Distilled water","1 cup White vinegar","¼ cup Rubbing alcohol","1 tsp Cornstarch","6 drops Lemon essential oil"]'::jsonb, '["Combine water, vinegar, and rubbing alcohol in a spray bottle.","Add cornstarch and shake until fully dissolved.","Add lemon oil and swirl gently to combine.","Spray onto glass and wipe with a microfiber cloth in straight lines.","Buff dry with a second clean cloth for a streak-free finish."]'::jsonb, false, '$2.40 saved', '["Streak-free"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('kitchen-spray', 'Kitchen Spray', 'Cleaning', 'cleaning', 'Easy', '4 min', '["1 cup White vinegar","1 cup Distilled water","from 2 lemons Lemon peels","1 tbsp Castile soap","10 drops Sweet orange oil"]'::jsonb, '["Pack lemon peels into a clean glass jar and cover with vinegar.","Seal and let infuse for 7 days in a dark cabinet (or skip for quick version).","Strain the lemon vinegar into a spray bottle.","Add distilled water, castile soap, and orange oil.","Swirl gently and label. Spray, let sit 30 seconds, wipe with a damp cloth."]'::jsonb, false, '$3.80 saved', '["Citrus","spray"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('floor-cleaner', 'Floor Cleaner', 'Cleaning', 'cleaning', 'Easy', '5 min', '["1 gallon Warm water","¼ cup Castile soap","½ cup White vinegar","2 tbsp Baking soda","15 drops Lemon essential oil"]'::jsonb, '["Fill a clean bucket with one gallon of warm water.","Stir in castile soap until evenly combined.","Add vinegar slowly, then sprinkle in baking soda (it will fizz briefly).","Drop in lemon oil and stir.","Mop in sections, rinsing the mop head between rooms. Air dry."]'::jsonb, false, '$4.10 saved', '["Pet-safe","family-safe"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('laundry-booster', 'Laundry Booster', 'Cleaning', 'cleaning', 'Easy', '2 min', '["1 cup Baking soda","1 cup Washing soda","½ cup Coarse sea salt","¼ cup Citric acid"]'::jsonb, '["Combine baking soda, washing soda, and sea salt in a large bowl.","Add citric acid and whisk until fully blended.","Transfer to a sealed glass jar — moisture will clump it.","Add 2 tablespoons per regular load, alongside your usual detergent.","For whites, add an extra tablespoon to the rinse cycle."]'::jsonb, false, '$2.80 saved', '["Fragrance-free"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('room-spray', 'Room Spray', 'Cleaning', 'cleaning', 'Easy', '3 min', '["¾ cup Distilled water","¼ cup Witch hazel","20 drops Lavender essential oil","10 drops Eucalyptus essential oil","6 drops Cedarwood essential oil"]'::jsonb, '["Pour witch hazel into a 4 oz glass spray bottle.","Add all essential oils and swirl gently for 10 seconds.","Top off with distilled water, leaving a half-inch at the top.","Cap and shake well. Let rest for 1 hour before first use.","Shake before each spray — mist toward the ceiling, never directly on fabric."]'::jsonb, false, '$5.20 saved', '["Calming","spray"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('sugar-scrub', 'Sugar Scrub', 'Beauty & Skincare', 'beauty-skincare', 'Easy', '6 min', '["1 cup Granulated sugar","½ cup, melted Coconut oil","2 tbsp Raw honey","1 tsp Vanilla extract","½ tsp Vitamin E oil"]'::jsonb, '["Gently melt coconut oil until just liquid — not hot.","In a bowl, combine sugar and melted coconut oil; stir until coated.","Add honey, vanilla, and vitamin E oil. Mix until smooth.","Spoon into a clean jar with a tight lid.","In the shower, scoop a small amount, massage in circles, rinse with warm water."]'::jsonb, false, '$8.50 saved', '["Glow","scrub"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('citrus-glow-scrub', 'Citrus Glow Scrub', 'Beauty & Skincare', 'beauty-skincare', 'Easy', '5 min', '["1 cup Granulated sugar","½ cup Coconut oil (melted)","1 tbsp Lemon zest","1 tbsp Orange zest","10–15 drops (optional) Lemon essential oil","5–10 drops (optional) Orange essential oil"]'::jsonb, '["In a bowl, mix sugar and coconut oil until fully combined.","Add lemon and orange zest.","Stir in essential oils if using.","Mix until the texture is soft and scoopable.","Transfer into a clean glass jar."]'::jsonb, false, '$11.00 saved', '["Brightening","Citrus","scrub"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('body-butter', 'Body Butter', 'Beauty & Skincare', 'beauty-skincare', 'Easy', '8 min', '["½ cup Shea butter","¼ cup Cocoa butter","¼ cup Sweet almond oil","2 tbsp Jojoba oil","1 tsp Vitamin E oil","10 drops Vanilla essential oil"]'::jsonb, '["In a heatproof bowl over simmering water, melt shea and cocoa butter.","Remove from heat. Stir in almond oil, jojoba oil, and vitamin E.","Refrigerate 25 – 35 minutes until edges are firm but center is soft.","Whip with a hand mixer on medium for 4 – 5 minutes until cloud-like.","Add vanilla oil, whip 30 more seconds, spoon into a jar, and store cool."]'::jsonb, false, '$11.00 saved', '["Whipped"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('candle', 'Soy Candle', 'Home & Air Freshening', 'home-air-freshening', 'Easy', '12 min', '["1 lb (~2 cups) Soy wax flakes","1 (pre-tabbed) Cotton candle wick","1 oz Fragrance oil (cozy blend)","1 Glass jar (8 oz)","1 Wick centering bar"]'::jsonb, '["Stick the wick tab to the center of the jar with a small dab of wax.","Melt soy wax in a double boiler to 180°F (82°C). Stir gently.","Remove from heat, let cool to 135°F (57°C), then add fragrance oil.","Pour slowly into the jar, leaving a half-inch at the top.","Set wick straight with a centering bar. Cool 24 hours before trimming wick to ¼\"."]'::jsonb, false, '$14.00 saved', '["Cozy","spray"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;
insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published) values ('linen-spray', 'Linen Mist', 'Home & Air Freshening', 'home-air-freshening', 'Easy', '4 min', '["¾ cup Distilled water","3 tbsp Witch hazel","25 drops Lavender essential oil","8 drops Roman chamomile oil","½ tsp Vegetable glycerin"]'::jsonb, '["Pour witch hazel into a 4 oz fine-mist glass bottle.","Add lavender and chamomile oils. Swirl 10 seconds.","Add glycerin (helps the scent linger longer on fabric).","Top with distilled water, leaving a half-inch headspace.","Cap, shake, and rest 30 minutes. Mist sheets 12\" away before bed."]'::jsonb, false, '$5.10 saved', '["Lavender","spray"]'::jsonb, 'catalog', true) on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags;

commit;
