-- 20 curated recipes added per design spec. All idempotent on conflict.
begin;

insert into public.recipes (id, title, category_label, category_key, difficulty, time_label, ingredients, instructions, safe_for_kids, cost_savings, tags, source, is_published, pantry_magic) values
  ('citrus-vinegar-cleaner', 'Citrus Vinegar All-Purpose Cleaner', 'Cleaning', 'cleaning', 'Easy', '10 min', '["Orange or lemon peels (enough to fill a jar)", "White vinegar (to cover)"]'::jsonb, '["Fill a jar with citrus peels.", "Cover completely with white vinegar.", "Seal and let sit 10–14 days in a cool, dark place.", "Strain out the peels.", "Dilute 1:1 with water in a spray bottle."]'::jsonb, true, '$5–$10 saved', '["kitchen", "all-purpose", "natural", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('hydrogen-peroxide-mold-spray', 'Hydrogen Peroxide Mold Spray', 'Cleaning', 'cleaning', 'Easy', '15 min', '["3% hydrogen peroxide (about 1 cup)"]'::jsonb, '["Pour 3% hydrogen peroxide into a spray bottle.", "Spray directly onto mold spots until saturated.", "Let sit for 10 minutes.", "Scrub gently with a brush, then rinse with clean water."]'::jsonb, false, '$4–$7 saved', '["bathroom", "mold", "antibacterial", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('diy-toilet-bombs', 'DIY Toilet Bombs', 'Cleaning', 'cleaning', 'Easy', '20 min', '["1 cup baking soda", "1/4 cup citric acid", "Water (in a spray bottle, for misting)"]'::jsonb, '["Mix baking soda and citric acid in a bowl.", "Lightly mist with water until the mixture is just moldable (don''t overdo it or it''ll fizz).", "Press firmly into silicone molds.", "Let dry overnight, then pop out and store in a sealed jar."]'::jsonb, true, '$6–$12 saved', '["bathroom", "toilet", "odor"]'::jsonb, 'catalog', true, false),
  ('castile-soap-floor-cleaner', 'Castile Soap Floor Cleaner', 'Cleaning', 'cleaning', 'Easy', '10 min', '["1 gallon warm water", "1 tbsp castile soap"]'::jsonb, '["Fill a bucket with warm water.", "Add the castile soap and stir gently to combine.", "Mop floors as usual — no rinse needed."]'::jsonb, true, '$5–$9 saved', '["floors", "wood", "tile", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('stainless-steel-polish', 'Stainless Steel Polish', 'Cleaning', 'cleaning', 'Easy', '5 min', '["White vinegar", "Olive oil"]'::jsonb, '["Wipe stainless surface with vinegar on a soft cloth.", "Buff with a small amount of olive oil along the grain.", "Wipe off any excess for a streak-free shine."]'::jsonb, true, '$3–$6 saved', '["kitchen", "appliances", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('dishwasher-deep-clean', 'Dishwasher Deep Clean Powder', 'Cleaning', 'cleaning', 'Easy', '5 min', '["1/2 cup baking soda", "1/4 cup citric acid"]'::jsonb, '["Sprinkle the baking soda across the bottom of an empty dishwasher.", "Place the citric acid in the detergent compartment.", "Run a hot cycle with no dishes."]'::jsonb, true, '$4–$8 saved', '["kitchen", "appliance"]'::jsonb, 'catalog', true, false),
  ('natural-drain-freshener', 'Natural Drain Freshener', 'Cleaning', 'cleaning', 'Easy', '5 min', '["1/2 cup baking soda", "1 cup white vinegar", "Hot water (for rinsing)"]'::jsonb, '["Pour the baking soda directly down the drain.", "Slowly pour the vinegar after it.", "Let it fizz for 10 minutes.", "Flush with hot tap water for 30 seconds."]'::jsonb, true, '$3–$6 saved', '["kitchen", "drain", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('linen-spray-fresh', 'Linen Spray', 'Home & Air Freshening', 'home-air-freshening', 'Easy', '5 min', '["3/4 cup distilled water", "2 tbsp witch hazel", "10–15 drops lavender essential oil"]'::jsonb, '["Combine all ingredients in a small spray bottle.", "Shake well before each use.", "Mist over linens, pillows, and curtains."]'::jsonb, true, '$5–$10 saved', '["fresh", "bedroom"]'::jsonb, 'catalog', true, false),
  ('wood-furniture-cream', 'DIY Wood Furniture Cream', 'Home & Air Freshening', 'home-air-freshening', 'Easy', '15 min', '["1/4 cup coconut oil", "1 tbsp grated beeswax"]'::jsonb, '["Combine coconut oil and beeswax in a heat-proof bowl over simmering water.", "Stir until fully melted and smooth.", "Pour into a small jar and let cool until solid (about 30 minutes).", "Apply a small amount to wood with a soft cloth, then buff."]'::jsonb, true, '$6–$12 saved', '["wood", "polish"]'::jsonb, 'catalog', true, false),
  ('closet-deodorizer-sachets', 'Closet Deodorizer Sachets', 'Home & Air Freshening', 'home-air-freshening', 'Easy', '10 min', '["1/2 cup baking soda", "2 tbsp dried herbs (lavender, rosemary, or sage)"]'::jsonb, '["Mix baking soda with the dried herbs in a bowl.", "Spoon into small cloth bags or breathable pouches.", "Tie shut and place in closets or drawers.", "Replace every 2–3 months."]'::jsonb, true, '$4–$8 saved', '["closet", "odor", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('air-gel-freshener', 'Natural Air Gel Freshener', 'Home & Air Freshening', 'home-air-freshening', 'Easy', '15 min', '["1 packet (1 tbsp) unflavored gelatin", "1 cup water", "10–15 drops essential oils"]'::jsonb, '["Bring 1/2 cup of the water to a boil.", "Stir in the gelatin until fully dissolved.", "Add the remaining 1/2 cup cold water and the essential oils.", "Pour into a small jar and let set in the fridge for 4 hours."]'::jsonb, true, '$5–$9 saved', '["air", "freshener"]'::jsonb, 'catalog', true, false),
  ('carpet-deodorizing-powder', 'Carpet Deodorizing Powder', 'Home & Air Freshening', 'home-air-freshening', 'Easy', '5 min', '["1 cup baking soda", "10–15 drops essential oil"]'::jsonb, '["Combine baking soda and essential oil in a jar with a shaker lid.", "Sprinkle generously over carpets and rugs.", "Wait 20 minutes.", "Vacuum thoroughly."]'::jsonb, true, '$5–$10 saved', '["carpet", "odor", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('diy-fabric-softener', 'DIY Fabric Softener', 'Laundry', 'laundry', 'Easy', '2 min', '["1/2 cup white vinegar", "10–15 drops essential oil (optional)"]'::jsonb, '["Combine vinegar and essential oil if using.", "Add to the rinse compartment of your washing machine.", "Run cycle as usual."]'::jsonb, true, '$6–$12 saved', '["laundry", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('window-track-cleaner-paste', 'Window Track Cleaner Paste', 'Home & Air Freshening', 'home-air-freshening', 'Easy', '10 min', '["1/4 cup baking soda", "Water (a few teaspoons)"]'::jsonb, '["Mix baking soda with just enough water to form a thick paste.", "Apply paste into window tracks with a small brush or old toothbrush.", "Scrub to lift dirt and grime.", "Wipe clean with a damp cloth."]'::jsonb, true, '$3–$6 saved', '["windows", "detail", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('oatmeal-soothing-bath', 'Oatmeal Soothing Bath', 'Beauty & Skincare', 'beauty-skincare', 'Easy', '5 min', '["1 cup ground oats (oatmeal blended fine)"]'::jsonb, '["Run a warm bath.", "Stir in the ground oats until milky.", "Soak for 15–20 minutes.", "Rinse off in the shower if desired."]'::jsonb, true, '$5–$10 saved', '["sensitive", "skin", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('sugar-lip-scrub', 'DIY Sugar Lip Scrub', 'Beauty & Skincare', 'beauty-skincare', 'Easy', '5 min', '["1 tbsp sugar", "1 tsp honey", "1 tsp coconut oil"]'::jsonb, '["Combine all ingredients in a small jar.", "Apply a pea-sized amount to clean lips.", "Massage gently in circles for 30 seconds.", "Wipe or rinse off."]'::jsonb, true, '$4–$8 saved', '["beauty", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('aloe-cooling-gel', 'Aloe Cooling Gel', 'Beauty & Skincare', 'beauty-skincare', 'Easy', '2 min', '["Aloe vera gel (fresh or store-bought, 100% pure)"]'::jsonb, '["Apply aloe vera gel directly to clean skin.", "Massage in until absorbed.", "Reapply as needed for cooling relief."]'::jsonb, true, '$5–$9 saved', '["skin", "soothing", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('natural-deodorant', 'Natural Deodorant Spray', 'Beauty & Skincare', 'beauty-skincare', 'Easy', '5 min', '["1/4 cup witch hazel", "1/4 cup distilled water", "10–15 drops essential oils (tea tree + lavender recommended)"]'::jsonb, '["Combine all ingredients in a small spray bottle.", "Shake well before each use.", "Spray onto clean, dry underarms."]'::jsonb, true, '$6–$12 saved', '["body"]'::jsonb, 'catalog', true, false),
  ('coconut-oil-hair-mask', 'Coconut Oil Hair Mask', 'Hair Care', 'hair-care', 'Easy', '30 min', '["2–3 tbsp coconut oil (warmed if solid)"]'::jsonb, '["Warm the coconut oil in your palms until liquid.", "Massage through dry hair, focusing on mid-lengths and ends.", "Leave on for 30 minutes (or overnight for deep conditioning).", "Wash out with shampoo, repeating if needed."]'::jsonb, true, '$8–$15 saved', '["hair", "pantry-magic"]'::jsonb, 'catalog', true, true),
  ('honey-face-cleanser', 'Honey Face Cleanser', 'Beauty & Skincare', 'beauty-skincare', 'Easy', '5 min', '["1 tsp raw honey"]'::jsonb, '["Wet face with warm water.", "Apply honey directly to skin.", "Massage in gentle circles for 1 minute.", "Rinse thoroughly with warm water and pat dry."]'::jsonb, true, '$6–$12 saved', '["face", "gentle", "pantry-magic"]'::jsonb, 'catalog', true, true)
on conflict (id) do update set
  title = excluded.title,
  category_label = excluded.category_label,
  category_key = excluded.category_key,
  difficulty = excluded.difficulty,
  time_label = excluded.time_label,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  safe_for_kids = excluded.safe_for_kids,
  cost_savings = excluded.cost_savings,
  tags = excluded.tags,
  pantry_magic = excluded.pantry_magic;

commit;
